### ISSUE TITLE
Email not received upon successful submission

### ISSUE THREAD

**Issue by theredcameron** [0xCoto/PICTOR#10]
I have submitted two requests for data from two different email addresses and have not received any data. Please confirm system is still operational.

**Comment by 0xCoto** [comment]
Hi @theredcameron 

The system _is_ indeed operational. What domain addresses have you used (gmail, hotmail...)? Did the emails arrive in spam by any chance? What parameters did you enter?

**Comment by theredcameron** [comment]
I use gmail.
Parameters:
Center Frequency: 1420
Bandwidth: 2.4 MHz
Number of Channels: 2048
Number of Bins: 1000
Duration: 10 seconds

**Comment by 0xCoto** [comment]
Can you share your email address (or send me an email to `0xcoto@protonmail.com` if you don't want to share it publicly here)? I'd like to run a test or two to check if the email gets sent to your address at all.

**Comment by sayan83** [comment]
Any updates on this?
Even I am having similar issues. I used it in October 2019 and it worked fine, but now I am not getting any emails.
Is it still functional?

**Comment by 0xCoto** [comment]
Hi @sayan83, looks like there was a momentary crash with the software. PICTOR should be working fine now.

**Comment by sayan83** [comment]
Thanks @0xCoto its working now.

**Comment by theredcameron** [comment]
I'm having these issues again. I've tried a number of different inputs, but I'm receiving no email. Please confirm the system is up and running.

**Comment by 0xCoto** [comment]
@theredcameron It appears that the name of the observation you entered is `'Mark's obvs'`, and the telescope is being confused with the quotes (trying to end the string earlier than intended). You can try adding a `\` before `'` like so: `'Mark\'s obvs'`, or more safely, not using the `'` character if not necessary.

**Comment by theredcameron** [comment]
Nevermind. It is working for me now.
