### ISSUE TITLE
Transpose data in CSV files

### ISSUE THREAD

**Issue by andy8025** [0xCoto/PICTOR#13]
Change the way data are stored in __data_spectrum.csv__ and __data_time_power.csv__ files that are emailed to user. Transpose rows and columns - to store samples in rows instead of columns.  

Current layout:

foo|1000|1001|1002|...
------------ | ------------- | ------------- | ------------- | -------------
__bar__|__2000__|__2001__|__2002__|__...__

Proposed layout:

foo|bar
------------ | -------------
__1000__|__2000__
__1001__|__2001__
__1002__|__2002__
__...__|__...__

Current CSV file layout prevents LibreOffice Calc from reading all the data. LibreOffice error: "The data could not be loaded completely because the maximum number of columns per sheet was exceeded".

**Comment by andy8025** [comment]
Made changes to __plot.py__ and __plot_hi.py__ to save the new transposed CSV files, in addition to the original CSV files. Did not modify the code in __observe.py__ that emails the CSV files.

Don't know how to check what Python libraries are available on the actual telescope system.  I see that NumPy is available, hope that Pandas is available as well :)

**Comment by ministerofsillywalks** [comment]
When I first did this, I wanted to use pandas to make the CSVs the way you want them, @0xCoto asked that I stick with just numpy instead.

**Comment by ministerofsillywalks** [comment]
You might be able to use np.transpose() https://note.nkmk.me/en/python-numpy-transpose/ without importing pandas.

**Comment by ministerofsillywalks** [comment]
You shouldn't need pandas because you can do the transposition without reopening the csvs, just do it before they are saved.

**Comment by andy8025** [comment]
Ok, I can try it in numpy.  Is it possible to get a copy of __observation.dat__, so that I may generate the __data_freq_zmean__ and __data_t_w__ numpy arrays?

**Comment by 0xCoto** [comment]
Thanks for the PR, just approved! The changes have been applied to the telescope, so feel free to try it out. :)
