### ISSUE TITLE
Time Series File showing Power to 3DP

### ISSUE THREAD

**Issue by davewyers** [0xCoto/PICTOR#18]
Hi There

Love your work.  I have a 2.3M dish that I have planning on going live with VIRGO in a couple of weeks, meanwhile I was generating some data with PICTOR to play with.

I ran a test on Pictor and when I looked at the Time Series data it appears that the Relative Power column is only showing 3DP "0.010" across all time time slots.  I am assuming that Column 1 is Time & Column 2 is Relative Power.

The graph is displaying values to 6DP.

See below.

![image](https://user-images.githubusercontent.com/8073328/116848516-e41e2f80-ac40-11eb-8b61-32a261129c2d.png)
![image](https://user-images.githubusercontent.com/8073328/116848611-1334a100-ac41-11eb-95ac-b0f91e26cba8.png)

**Comment by 0xCoto** [comment]
Thanks for the feedback!

I've just pushed this fix to Virgo 3.6.7 and updated PICTOR to use that. The precision has been increased to 6 decimal places and is now much more readable.

And yup, the first column is indeed time and the second is the relative power.

**Comment by davewyers** [comment]
Perfect, I have just tested and can confirm the fix.

What is the best way to interact around PICTOR & VIRGO outside of issues, do you have a user forum?

Regards
Dave 

![image](https://user-images.githubusercontent.com/8073328/116947065-e8455e00-accf-11eb-8e61-e498337a241b.png)

**Comment by 0xCoto** [comment]
There used to be a Discourse page (forum) for discussions related to PICTOR and (radio) astronomy, but maintenance was a bit costly (mostly in terms of my time, and partially hosting costs as CPU allocation is higher hosting more web pages online).

**Comment by davewyers** [comment]
Ok understood, thanks
