### ISSUE TITLE
Old Link

### ISSUE THREAD

**Issue by Kaffeedor** [0xCoto/PICTOR#20]
![image](https://user-images.githubusercontent.com/49571205/133075542-0f9f0979-9582-4846-be95-6287c66eb887.png)
![image](https://user-images.githubusercontent.com/49571205/133075553-0ec08439-1def-4906-96df-80a40db53f90.png)
Yannicks GitHub link doesnt work (anymore?)

**Comment by 0xCoto** [comment]
Resolved.
