### ISSUE TITLE
Running Instructions

### ISSUE THREAD

**Issue by SteveBz** [0xCoto/PICTOR#22]
Hi Apostolos,

Hope you are well.  My feedhorn is pretty much there, the RTL.SDR is installed and polling.  I just need to mount the stand, the dish and the feedhorne, connect the LNA and the RTL.SDR and install the software (yours).  I say 'just' I'm sure there will be a lot of problem-solving.

Are there some installation or running instructions for your code?  Do I just download them into a directory and type python3 xxxxxxxxx.py or something?

Please could you update the readme with how to do it?  

Tx

Kind regards

Steve.

**Comment by 0xCoto** [comment]
@SteveBz Hi Steve,

I'd suggestion checking out Virgo - this should help you get started with running the acquisition/analysis software on your own machine: https://github.com/0xCoto/Virgo
Documentation: https://virgo.readthedocs.io/en/latest/

PICTOR is based on Virgo, with a few extra functions for communicating data to the user over an online platform etc.
